<!doctype html>
<html lang="es"><head><meta charset="utf-8"><title>HINE · {{ $patient->full_name }}</title>
<style>@page{size:A4;margin:12mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#1e293b;margin:0;font-size:10px}.toolbar{padding:10px 0;border-bottom:1px solid #ddd;margin-bottom:14px}.btn{border:0;border-radius:8px;padding:9px 14px;font-weight:700;cursor:pointer}.primary{background:#6d28d9;color:#fff}.secondary{background:#e2e8f0}.head{display:flex;justify-content:space-between;gap:20px;border-bottom:3px solid #6d28d9;padding-bottom:10px}.brand{font-size:20px;font-weight:900;color:#5b21b6}.muted{color:#64748b}.score{text-align:right;font-size:27px;font-weight:900;color:#5b21b6}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:12px}.box{border:1px solid #dbe4ee;border-radius:8px;padding:8px}.section{margin-top:15px;break-inside:avoid}.section h2{font-size:13px;color:#5b21b6;border-bottom:1px solid #ddd;padding-bottom:4px;margin:0 0 7px}.scores{display:grid;grid-template-columns:repeat(5,1fr);gap:6px}.scores .box{text-align:center}.scores strong{font-size:16px}.bar{height:6px;background:#e2e8f0;border-radius:6px;margin-top:5px;overflow:hidden}.fill{height:100%;background:#0891b2}table{width:100%;border-collapse:collapse;margin-top:5px}th,td{border:1px solid #dbe4ee;padding:5px;vertical-align:top}th{background:#f1f5f9;text-align:left;font-size:9px}.item{font-weight:700}.small{font-size:9px}.footer{margin-top:18px;border-top:1px solid #ddd;padding-top:7px;color:#64748b;font-size:8.5px}.page-break{break-before:page}@media print{.toolbar{display:none}.section{break-inside:avoid}}</style></head><body>
<div class="toolbar"><button class="btn primary" onclick="window.print()">Imprimir / Guardar como PDF</button> <button class="btn secondary" onclick="window.close()">Cerrar</button></div>
<header class="head"><div><div class="brand">URPE · Evaluación HINE</div><strong>{{ $patient->full_name }}</strong><div class="muted">Fecha: {{ $assessment->examination_date->format('d/m/Y') }} · HINE {{ $assessment->instrument_version }}</div><div class="muted">{{ $assessment->status === 'finalized' ? 'Finalizada' : 'Borrador' }} · {{ $assessment->author?->name ?: 'Profesional no disponible' }}</div></div><div><div class="score">{{ $hine->global_score ?? '—' }} / 78</div><div class="muted" style="text-align:right">Asimetrías: {{ $hine->asymmetry_count ?? 0 }}</div></div></header>
<div class="grid"><div class="box"><strong>Edad gestacional</strong><br>{{ $hine->gestational_age ?: '—' }}</div><div class="box"><strong>Edad cronológica</strong><br>{{ $hine->chronological_age ?: '—' }}</div><div class="box"><strong>Edad corregida</strong><br>{{ $hine->corrected_age ?: '—' }}</div><div class="box"><strong>Perímetro cefálico</strong><br>{{ $hine->head_circumference ?: '—' }}</div><div class="box" style="grid-column:span 2"><strong>Comentarios generales</strong><br>{{ $hine->general_comments ?: '—' }}</div></div>
<section class="section"><h2>Resumen neurológico</h2><div class="scores">@foreach([['Pares craneales',$hine->cranial_nerves_score,15],['Postura',$hine->posture_score,18],['Movimientos',$hine->movements_score,6],['Tono',$hine->tone_score,24],['Reflejos / reacciones',$hine->reflexes_reactions_score,15]] as $s)<div class="box"><div class="small">{{ $s[0] }}</div><strong>{{ $s[1] ?? '—' }}/{{ $s[2] }}</strong><div class="bar"><div class="fill" style="width:{{ $s[1] !== null ? min(100, ((float)$s[1]/$s[2])*100) : 0 }}%"></div></div></div>@endforeach</div></section>
<section class="section"><h2>1. Examen neurológico</h2><table><thead><tr><th>Sección / ítem</th><th>Punt.</th><th>Lado</th><th>Asim.</th><th>Comentarios</th></tr></thead><tbody>@foreach($sections as $sectionKey=>$section)@foreach($section['items'] as $item)@php($response=$responses->get($item['key']))<tr><td class="item">{{ $section['label'] }} · {{ $item['label'] }}</td><td>{{ $response?->score ?? '—' }}</td><td>—</td><td>{{ $response?->asymmetry ? 'Sí' : 'No' }}</td><td>{{ $response?->comments ?: '—' }}</td></tr>@endforeach @endforeach</tbody></table></section>
<section class="section page-break"><h2>2. Hitos motores</h2><table><thead><tr><th>Hito</th><th>Observado</th><th>Edad de adquisición</th><th>Comentarios</th></tr></thead><tbody>@foreach($motorMilestones as $milestone)@php($r=$responses->get($milestone['key']))<tr><td class="item">{{ $milestone['label'] }}</td><td>{{ data_get($r?->response_data, 'observed') ?: '—' }}</td><td>{{ data_get($r?->response_data, 'acquisition_age') ?: '—' }}</td><td>{{ $r?->comments ?: '—' }}</td></tr>@endforeach</tbody></table></section>
<section class="section"><h2>3. Comportamiento</h2><table><thead><tr><th>Ítem</th><th>Respuesta registrada</th><th>Comentarios</th></tr></thead><tbody>@foreach($behaviorItems as $item)@php($r=$responses->get($item['key']))@php($option=data_get($r?->response_data, 'option'))<tr><td class="item">{{ $item['label'] }}</td><td>{{ $option !== null && isset($item['options'][(int) $option]) ? $item['options'][(int) $option] : '—' }}</td><td>{{ $r?->comments ?: '—' }}</td></tr>@endforeach</tbody></table></section>
<section class="section"><h2>Apoyo para la interpretación</h2><p>{{ $interpretation['note'] }}</p><p><strong>{{ $interpretation['global_score_heading'] }}:</strong> @foreach($interpretation['global_score_ranges'] as $range) {{ $range['label'] }}@if(!$loop->last) · @endif @endforeach</p><p><strong>{{ $interpretation['high_risk_heading'] }}:</strong> @foreach($interpretation['high_risk_cutoffs_by_age_months'] as $age=>$cutoff) {{ $age }} meses: {{ $cutoff }}@if(!$loop->last) · @endif @endforeach</p></section>
<div class="footer">URPE Gestión Clínica · Documento generado desde la evaluación HINE registrada en el sistema. La información de interpretación es material de apoyo y no constituye por sí sola un diagnóstico.</div></body></html>